apiVersion: v1
items:
- apiVersion: v1
  kind: Service
  metadata:
    creationTimestamp: "2024-10-11T13:25:23Z"
    labels:
      app: myd
      app.kubernetes.io/instance: webapp
    name: myd
    resourceVersion: "4651"
    uid: fd5d9605-26c9-49c9-8d58-b535565d4b8d
  spec:
    clusterIP: 10.104.132.58
    clusterIPs:
    - 10.104.132.58
    externalTrafficPolicy: Cluster
    internalTrafficPolicy: Cluster
    ipFamilies:
    - IPv4
    ipFamilyPolicy: SingleStack
    ports:
    - nodePort: 30493
      port: 80
      protocol: TCP
      targetPort: 80
    selector:
      app: myd
    sessionAffinity: None
    type: NodePort
  status:
    loadBalancer: {}
kind: List
metadata:
  resourceVersion: ""
